services:
  - type: web
    name: single-point-of-contact
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn djangoProject.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: single-point-of-contact-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: xok1611995@yandex.ru
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: xok1611995@yandex.ru
      - key: ALLOWED_HOSTS
        value: single-point-of-contact.onrender.com

databases:
  - name: single-point-of-contact-db
    plan: free
    databaseName: single_point_of_contact
    user: single_point_of_contact_user

