# Generated by Django 5.0.4 on 2024-04-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
