# Generated by Django 5.1.3 on 2024-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0003_article_audio_article_image_article_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Uncategorized', max_length=50)),
                ('status', models.CharField(default='New', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('another_field', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'another_field'], name='knowledgeba_name_0fa9f1_idx')],
            },
        ),
    ]
