# Generated by Django 4.2.7 on 2024-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_request_mymodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status', 'category'], name='knowledgeba_status_b23b6f_idx'),
        ),
    ]
