# Generated by Django 5.2.7 on 2025-11-14 02:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0008_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Technical', 'Техническая'), ('Content', 'Контент'), ('Other', 'Другое'), ('Uncategorized', 'Без категории')], default='Uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В работе'), ('Completed', 'Завершена'), ('Cancelled', 'Отменена')], default='New', max_length=50),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-pub_date'], name='knowledgeba_pub_dat_ec2b56_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='knowledgeba_title_d683f9_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='knowledgeba_created_770034_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article'], name='knowledgeba_article_f66fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['request'], name='knowledgeba_request_5bbea2_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='knowledgeba_status_3e5b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['category'], name='knowledgeba_categor_f26a3a_idx'),
        ),
    ]
