# Generated by Django 5.1.3 on 2025-11-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0010_article_author_request_created_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='knowledgeba_author__3bd697_idx',
            old_name='knowledgeba_author_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='request',
            new_name='knowledgeba_created_c5a4fa_idx',
            old_name='knowledgeba_created_789abc_idx',
        ),
    ]
